---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - barbican.openstack.org
  resources:
  - barbicanapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftproxies/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftrings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftrings/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftrings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - swift.openstack.org
  resources:
  - swifts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swifts/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - swift.openstack.org
  resources:
  - swifts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftstorages/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftstorages/status
  verbs:
  - get
  - patch
  - update
